<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LTIN509463" failures="0" tests="8" name="TestCases.TC_001_TravelInsurance" time="37.536" errors="1" timestamp="2024-04-15T13:05:32 IST" skipped="0">
  <testcase classname="TestCases.TC_001_TravelInsurance" name="travelInsuranceButton" time="0.213"/>
  <testcase classname="TestCases.TC_001_TravelInsurance" name="destinationDetails" time="5.703"/>
  <testcase classname="TestCases.TC_001_TravelInsurance" name="tripDateDetails" time="2.695"/>
  <testcase classname="TestCases.TC_001_TravelInsurance" name="travellersDetails" time="10.936"/>
  <testcase classname="TestCases.TC_001_TravelInsurance" name="medicalHistoryDetails" time="0.624"/>
  <testcase classname="TestCases.TC_001_TravelInsurance" name="contactDetails" time="2.160"/>
  <testcase classname="TestCases.TC_001_TravelInsurance" name="planType" time="12.168">
    <error message="C:\Users\2327176\eclipse-workspace\Hackathon_TravelInsurance\testdata\ExcelWrite.xlsx (The process cannot access the file because it is being used by another process)" type="java.io.FileNotFoundException">
      <![CDATA[java.io.FileNotFoundException: C:\Users\2327176\eclipse-workspace\Hackathon_TravelInsurance\testdata\ExcelWrite.xlsx (The process cannot access the file because it is being used by another process)
at java.base/java.io.FileOutputStream.open0(Native Method)
at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:123)
at utilities.ExcelUtility.setcelldata(ExcelUtility.java:39)
at pageObjects.TravelInsurance.printInsuranceCompanyName(TravelInsurance.java:267)
at TestCases.TC_001_TravelInsurance.planType(TC_001_TravelInsurance.java:78)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- planType -->
  <testcase classname="TestCases.TC_001_TravelInsurance" name="homePage" time="3.037"/>
</testsuite> <!-- TestCases.TC_001_TravelInsurance -->
